FROM python:3.9-slim as builder

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt


FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages

COPY . .

RUN pip install -r requirements.txt

EXPOSE 8081

CMD ["python", "./main.py"]
